### ISSUE TITLE
Unable to build via the universal-resolver

### ISSUE THREAD

**Issue by CluEleSsUK** [Sphereon-Opensource/uni-resolver-driver-did-factom#6] opened 2021-04-07 09:24 UTC
Hi there,

I have just tried to run the (universal-resolver)[https://github.com/decentralized-identity/universal-resolver], of which this driver is a part but the did-factom driver build failed with the following logs:

```
Attaching to universal-resolver_driver-did-factom_1
driver-did-factom_1              | export HOME='/root'
driver-did-factom_1              | export HOSTNAME='5fbd67f51f6c'
driver-did-factom_1              | export JAVA_HOME='/usr/lib/jvm/java-8-openjdk-amd64/'
driver-did-factom_1              | export NODE1_ENABLED='true'
driver-did-factom_1              | export NODE1_FACTOMD_URL='https://api.factomd.net/v2'
driver-did-factom_1              | export NODE1_NETWORK_ID='mainnet'
driver-did-factom_1              | export NODE2_ENABLED='true'
driver-did-factom_1              | export NODE2_FACTOMD_URL='https://dev.factomd.net/v2'
driver-did-factom_1              | export NODE2_NETWORK_ID='testnet'
driver-did-factom_1              | export OLDPWD='/'
driver-did-factom_1              | export PATH='/usr/lib/jvm/java-8-openjdk-amd64//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
driver-did-factom_1              | export PWD='/opt/driver-did-factom'
driver-did-factom_1              | [INFO] Scanning for projects...
driver-did-factom_1              | [WARNING]
driver-did-factom_1              | [WARNING] Some problems were encountered while building the effective model for decentralized-identity:uni-resolver-driver-did-factom:war:0.1-SNAPSHOT
driver-did-factom_1              | [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 19, column 21
driver-did-factom_1              | [WARNING]
driver-did-factom_1              | [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
driver-did-factom_1              | [WARNING]
driver-did-factom_1              | [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
driver-did-factom_1              | [WARNING]
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/maven-metadata.xml (867 B at 226 B/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/3.2.0/maven-jar-plugin-3.2.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/3.2.0/maven-jar-plugin-3.2.0.pom (7.3 kB at 28 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/3.2.0/maven-jar-plugin-3.2.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/3.2.0/maven-jar-plugin-3.2.0.jar (29 kB at 72 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/3.0.0-M1/maven-release-plugin-3.0.0-M1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/3.0.0-M1/maven-release-plugin-3.0.0-M1.pom (9.5 kB at 75 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/release/maven-release/3.0.0-M1/maven-release-3.0.0-M1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/release/maven-release/3.0.0-M1/maven-release-3.0.0-M1.pom (7.5 kB at 55 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/3.0.0-M1/maven-release-plugin-3.0.0-M1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/3.0.0-M1/maven-release-plugin-3.0.0-M1.jar (59 kB at 135 kB/s)
driver-did-factom_1              | [INFO]
driver-did-factom_1              | [INFO] -------< decentralized-identity:uni-resolver-driver-did-factom >--------
driver-did-factom_1              | [INFO] Building uni-resolver-driver-did-factom 0.1-SNAPSHOT
driver-did-factom_1              | [INFO] --------------------------------[ war ]---------------------------------
driver-did-factom_1              | [INFO]
driver-did-factom_1              | [INFO] >>> jetty-maven-plugin:9.4.18.v20190429:run (default-cli) > test-compile @ uni-resolver-driver-did-factom >>>
driver-did-factom_1              | Downloading from github-did-common-java: https://maven.pkg.github.com/decentralized-identity/did-common-java/org/factomprotocol/identity/factom-identity-client/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/factomprotocol/identity/factom-identity-client/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/factomprotocol/identity/factom-identity-client/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-universal-resolver: https://maven.pkg.github.com/decentralized-identity/universal-resolver/org/factomprotocol/identity/factom-identity-client/0.3.0-SNAPSHOT/maven-metadata.xml
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/factomprotocol/identity/factom-identity-client/0.3.0-SNAPSHOT/maven-metadata.xml (979 B at 730 B/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/factomprotocol/identity/factom-identity-client/0.3.0-SNAPSHOT/factom-identity-client-0.3.0-20210119.155858-15.pom
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/factomprotocol/identity/factom-identity-client/0.3.0-SNAPSHOT/factom-identity-client-0.3.0-20210119.155858-15.pom
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/factomprotocol/identity/factom-identity-client/0.3.0-SNAPSHOT/factom-identity-client-0.3.0-20210119.155858-15.pom (2.9 kB at 13 kB/s)
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-api/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/blockchain-innovation/factom/client/factom-client-api/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-universal-resolver: https://maven.pkg.github.com/decentralized-identity/universal-resolver/org/blockchain-innovation/factom/client/factom-client-api/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-did-common-java: https://maven.pkg.github.com/decentralized-identity/did-common-java/org/blockchain-innovation/factom/client/factom-client-api/0.3.0-SNAPSHOT/maven-metadata.xml
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-api/0.3.0-SNAPSHOT/maven-metadata.xml (1.4 kB at 6.9 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/blockchain-innovation/factom/client/factom-client-api/0.3.0-SNAPSHOT/factom-client-api-0.3.0-20210112.105615-10.pom
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-api/0.3.0-SNAPSHOT/factom-client-api-0.3.0-20210112.105615-10.pom
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-api/0.3.0-SNAPSHOT/factom-client-api-0.3.0-20210112.105615-10.pom (1.6 kB at 8.6 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/blockchain-innovation/factom/client/factom-client-impl/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-did-common-java: https://maven.pkg.github.com/decentralized-identity/did-common-java/org/blockchain-innovation/factom/client/factom-client-impl/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-impl/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-universal-resolver: https://maven.pkg.github.com/decentralized-identity/universal-resolver/org/blockchain-innovation/factom/client/factom-client-impl/0.3.0-SNAPSHOT/maven-metadata.xml
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-impl/0.3.0-SNAPSHOT/maven-metadata.xml (1.4 kB at 5.4 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/blockchain-innovation/factom/client/factom-client-impl/0.3.0-SNAPSHOT/factom-client-impl-0.3.0-20210112.105615-9.pom
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-impl/0.3.0-SNAPSHOT/factom-client-impl-0.3.0-20210112.105615-9.pom
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-impl/0.3.0-SNAPSHOT/factom-client-impl-0.3.0-20210112.105615-9.pom (1.7 kB at 8.5 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/blockchain-innovation/factom/client/factom-client-offline-signing/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-did-common-java: https://maven.pkg.github.com/decentralized-identity/did-common-java/org/blockchain-innovation/factom/client/factom-client-offline-signing/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-universal-resolver: https://maven.pkg.github.com/decentralized-identity/universal-resolver/org/blockchain-innovation/factom/client/factom-client-offline-signing/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-offline-signing/0.3.0-SNAPSHOT/maven-metadata.xml
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-offline-signing/0.3.0-SNAPSHOT/maven-metadata.xml (1.4 kB at 4.9 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/blockchain-innovation/factom/client/factom-client-offline-signing/0.3.0-SNAPSHOT/factom-client-offline-signing-0.3.0-20210112.105615-9.pom
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-offline-signing/0.3.0-SNAPSHOT/factom-client-offline-signing-0.3.0-20210112.105615-9.pom
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-offline-signing/0.3.0-SNAPSHOT/factom-client-offline-signing-0.3.0-20210112.105615-9.pom (1.9 kB at 10 kB/s)
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/decentralized-identity/did-common-java/0.3-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/decentralized-identity/did-common-java/0.3-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-universal-resolver: https://maven.pkg.github.com/decentralized-identity/universal-resolver/decentralized-identity/did-common-java/0.3-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-did-common-java: https://maven.pkg.github.com/decentralized-identity/did-common-java/decentralized-identity/did-common-java/0.3-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/decentralized-identity/did-common-java/0.3-SNAPSHOT/did-common-java-0.3-SNAPSHOT.pom
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/decentralized-identity/did-common-java/0.3-SNAPSHOT/did-common-java-0.3-SNAPSHOT.pom
driver-did-factom_1              | Downloading from github-universal-resolver: https://maven.pkg.github.com/decentralized-identity/universal-resolver/decentralized-identity/did-common-java/0.3-SNAPSHOT/did-common-java-0.3-SNAPSHOT.pom
driver-did-factom_1              | Downloading from github-did-common-java: https://maven.pkg.github.com/decentralized-identity/did-common-java/decentralized-identity/did-common-java/0.3-SNAPSHOT/did-common-java-0.3-SNAPSHOT.pom
driver-did-factom_1              | [WARNING] The POM for decentralized-identity:did-common-java:jar:0.3-SNAPSHOT is missing, no dependency information available
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/factomprotocol/identity/factom-did-models-java-gson/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-did-common-java: https://maven.pkg.github.com/decentralized-identity/did-common-java/org/factomprotocol/identity/factom-did-models-java-gson/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/factomprotocol/identity/factom-did-models-java-gson/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-universal-resolver: https://maven.pkg.github.com/decentralized-identity/universal-resolver/org/factomprotocol/identity/factom-did-models-java-gson/0.3.0-SNAPSHOT/maven-metadata.xml
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/factomprotocol/identity/factom-did-models-java-gson/0.3.0-SNAPSHOT/maven-metadata.xml (1.4 kB at 4.3 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/blockchain-innovation/factom/client/json-converter-gson/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/json-converter-gson/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-did-common-java: https://maven.pkg.github.com/decentralized-identity/did-common-java/org/blockchain-innovation/factom/client/json-converter-gson/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-universal-resolver: https://maven.pkg.github.com/decentralized-identity/universal-resolver/org/blockchain-innovation/factom/client/json-converter-gson/0.3.0-SNAPSHOT/maven-metadata.xml
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/json-converter-gson/0.3.0-SNAPSHOT/maven-metadata.xml (1.4 kB at 8.3 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/blockchain-innovation/factom/client/json-converter-gson/0.3.0-SNAPSHOT/json-converter-gson-0.3.0-20210112.105615-9.pom
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/json-converter-gson/0.3.0-SNAPSHOT/json-converter-gson-0.3.0-20210112.105615-9.pom
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/json-converter-gson/0.3.0-SNAPSHOT/json-converter-gson-0.3.0-20210112.105615-9.pom (1.9 kB at 10 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/blockchain-innovation/factom/client/logger-slf4j/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/logger-slf4j/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-universal-resolver: https://maven.pkg.github.com/decentralized-identity/universal-resolver/org/blockchain-innovation/factom/client/logger-slf4j/0.3.0-SNAPSHOT/maven-metadata.xml
driver-did-factom_1              | Downloading from github-did-common-java: https://maven.pkg.github.com/decentralized-identity/did-common-java/org/blockchain-innovation/factom/client/logger-slf4j/0.3.0-SNAPSHOT/maven-metadata.xml
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/logger-slf4j/0.3.0-SNAPSHOT/maven-metadata.xml (1.4 kB at 7.8 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/org/blockchain-innovation/factom/client/logger-slf4j/0.3.0-SNAPSHOT/logger-slf4j-0.3.0-20210112.105615-9.pom
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/logger-slf4j/0.3.0-SNAPSHOT/logger-slf4j-0.3.0-20210112.105615-9.pom
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/logger-slf4j/0.3.0-SNAPSHOT/logger-slf4j-0.3.0-20210112.105615-9.pom (1.8 kB at 9.8 kB/s)
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/factomprotocol/identity/factom-identity-client/0.3.0-SNAPSHOT/factom-identity-client-0.3.0-20210119.155858-15.jar
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-impl/0.3.0-SNAPSHOT/factom-client-impl-0.3.0-20210112.105615-9.jar
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-api/0.3.0-SNAPSHOT/factom-client-api-0.3.0-20210112.105615-10.jar
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/json-converter-gson/0.3.0-SNAPSHOT/json-converter-gson-0.3.0-20210112.105615-9.jar
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-offline-signing/0.3.0-SNAPSHOT/factom-client-offline-signing-0.3.0-20210112.105615-9.jar
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/json-converter-gson/0.3.0-SNAPSHOT/json-converter-gson-0.3.0-20210112.105615-9.jar (6.1 kB at 21 kB/s)
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/logger-slf4j/0.3.0-SNAPSHOT/logger-slf4j-0.3.0-20210112.105615-9.jar
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-impl/0.3.0-SNAPSHOT/factom-client-impl-0.3.0-20210112.105615-9.jar (41 kB at 109 kB/s)
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-offline-signing/0.3.0-SNAPSHOT/factom-client-offline-signing-0.3.0-20210112.105615-9.jar (12 kB at 24 kB/s)
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/logger-slf4j/0.3.0-SNAPSHOT/logger-slf4j-0.3.0-20210112.105615-9.jar (3.5 kB at 6.1 kB/s)
Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/factomprotocol/identity/factom-identity-client/0.3.0-SNAPSHOT/factom-identity-client-0.3.0-20210119.155858-15.jar (75 kB at 109 kB/s)
driver-did-factom_1              | Downloaded from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/org/blockchain-innovation/factom/client/factom-client-api/0.3.0-SNAPSHOT/factom-client-api-0.3.0-20210112.105615-10.jar (134 kB at 176 kB/s)
driver-did-factom_1              | Downloading from central: https://repo.maven.apache.org/maven2/decentralized-identity/did-common-java/0.3-SNAPSHOT/did-common-java-0.3-SNAPSHOT.jar
driver-did-factom_1              | Downloading from sphereon-opensource-snapshots: http://nexus.qa.sphereon.com/repository/sphereon-opensource-snapshots/decentralized-identity/did-common-java/0.3-SNAPSHOT/did-common-java-0.3-SNAPSHOT.jar
driver-did-factom_1              | Downloading from github-universal-resolver: https://maven.pkg.github.com/decentralized-identity/universal-resolver/decentralized-identity/did-common-java/0.3-SNAPSHOT/did-common-java-0.3-SNAPSHOT.jar
driver-did-factom_1              | Downloading from github-did-common-java: https://maven.pkg.github.com/decentralized-identity/did-common-java/decentralized-identity/did-common-java/0.3-SNAPSHOT/did-common-java-0.3-SNAPSHOT.jar
driver-did-factom_1              | [INFO] ------------------------------------------------------------------------
driver-did-factom_1              | [INFO] BUILD FAILURE
driver-did-factom_1              | [INFO] ------------------------------------------------------------------------
driver-did-factom_1              | [INFO] Total time:  30.041 s
driver-did-factom_1              | [INFO] Finished at: 2021-04-07T09:11:19Z
driver-did-factom_1              | [INFO] ------------------------------------------------------------------------
driver-did-factom_1              | [ERROR] Failed to execute goal on project uni-resolver-driver-did-factom: Could not resolve dependencies for project decentralized-identity:uni-resolver-driver-did-factom:war:0.1-SNAPSHOT: Could not find artifact decentralized-identity:did-common-java:jar:0.3-SNAPSHOT in central (https://repo.maven.apache.org/maven2) -> [Help 1]
driver-did-factom_1              | [ERROR]
driver-did-factom_1              | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
driver-did-factom_1              | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
driver-did-factom_1              | [ERROR]
driver-did-factom_1              | [ERROR] For more information about the errors and possible solutions, please read the following articles:
driver-did-factom_1              | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
driver-did-factom_1              | export HOME='/root'
driver-did-factom_1              | export HOSTNAME='5fbd67f51f6c'
driver-did-factom_1              | export JAVA_HOME='/usr/lib/jvm/java-8-openjdk-amd64/'
driver-did-factom_1              | export NODE1_ENABLED='true'
driver-did-factom_1              | export NODE1_FACTOMD_URL='https://api.factomd.net/v2'
driver-did-factom_1              | export NODE1_NETWORK_ID='mainnet'
driver-did-factom_1              | export NODE2_ENABLED='true'
driver-did-factom_1              | export NODE2_FACTOMD_URL='https://dev.factomd.net/v2'
driver-did-factom_1              | export NODE2_NETWORK_ID='testnet'
driver-did-factom_1              | export OLDPWD='/'
driver-did-factom_1              | export PATH='/usr/lib/jvm/java-8-openjdk-amd64//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
driver-did-factom_1              | export PWD='/opt/driver-did-factom'
driver-did-factom_1              | [INFO] Scanning for projects...
driver-did-factom_1              | [WARNING]
driver-did-factom_1              | [WARNING] Some problems were encountered while building the effective model for decentralized-identity:uni-resolver-driver-did-factom:war:0.1-SNAPSHOT
driver-did-factom_1              | [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 19, column 21
driver-did-factom_1              | [WARNING]
driver-did-factom_1              | [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
driver-did-factom_1              | [WARNING]
driver-did-factom_1              | [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
driver-did-factom_1              | [WARNING]
driver-did-factom_1              | [INFO]
driver-did-factom_1              | [INFO] -------< decentralized-identity:uni-resolver-driver-did-factom >--------
driver-did-factom_1              | [INFO] Building uni-resolver-driver-did-factom 0.1-SNAPSHOT
driver-did-factom_1              | [INFO] --------------------------------[ war ]---------------------------------
driver-did-factom_1              | [INFO]
driver-did-factom_1              | [INFO] >>> jetty-maven-plugin:9.4.18.v20190429:run (default-cli) > test-compile @ uni-resolver-driver-did-factom >>>
driver-did-factom_1              | [WARNING] The POM for decentralized-identity:did-common-java:jar:0.3-SNAPSHOT is missing, no dependency information available
driver-did-factom_1              | [INFO] ------------------------------------------------------------------------
driver-did-factom_1              | [INFO] BUILD FAILURE
driver-did-factom_1              | [INFO] ------------------------------------------------------------------------
driver-did-factom_1              | [INFO] Total time:  6.927 s
driver-did-factom_1              | [INFO] Finished at: 2021-04-07T09:16:10Z
driver-did-factom_1              | [INFO] ------------------------------------------------------------------------
driver-did-factom_1              | [ERROR] Failed to execute goal on project uni-resolver-driver-did-factom: Could not resolve dependencies for project decentralized-identity:uni-resolver-driver-did-factom:war:0.1-SNAPSHOT: Failure to find decentralized-identity:did-common-java:jar:0.3-SNAPSHOT in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
driver-did-factom_1              | [ERROR]
driver-did-factom_1              | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
driver-did-factom_1              | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
driver-did-factom_1              | [ERROR]
driver-did-factom_1              | [ERROR] For more information about the errors and possible solutions, please read the following articles:
driver-did-factom_1              | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
universal-resolver_driver-did-factom_1 exited with code 1
```

I'm running the following:
OSX Catalina 10.15
Docker version 20.10.5, build 55c4c88
docker-compose version 1.28.5, build c4eb3a1f

**Comment by BernhardFuchs** [comment] 2021-04-14 13:18
We are having the same issue on the public Universal Resolver. The root cause is a wrong repository host for `did-common-java` at:  
```
Downloading from github-universal-resolver: https://maven.pkg.github.com/decentralized-identity/universal-resolver/decentralized-identity/did-common-java/0.3-SNAPSHOT/did-common-java-0.3-SNAPSHOT.jar
Downloading from github-did-common-java: https://maven.pkg.github.com/decentralized-identity/did-common-java/decentralized-identity/did-common-java/0.3-SNAPSHOT/did-common-java-0.3-SNAPSHOT.jar
```

The correct host is `https://repo.danubetech.com`. We migrated to a self-hosted solution a while ago and although some old versions are still available on `https://maven.pkg.github.com`, this repo is not updated anymore.

**Comment by BernhardFuchs** [comment] 2021-07-08 10:04
The driver got removed with https://github.com/decentralized-identity/universal-resolver/pull/220 because it is not booting  
Once the image is fixed feel free to create a PR for adding the driver again

**Comment by nklomp** [comment] 2021-08-20 15:07
A new PR has been merged for an updated version of the driver, that does not build itself.
https://github.com/decentralized-identity/universal-resolver/pull/234

Sorry for noticing so late!

**Closed as completed by nklomp** 2021-08-20 15:07 UTC
